better Jenkinsfile

diff --git a/Jenkinsfile.master b/Jenkinsfile.master
--- a/Jenkinsfile.master
+++ b/Jenkinsfile.master
@@ -6,10 +6,32 @@ pipeline {
     }
 
     stages {
-        stage ("Build") {
-           steps {
-              echo "Building"
-           }
+        stage("Build") {
+            steps {
+                echo "Building"
+                sh """
+                if docker image rm -f http-server:build; then
+	                echo Previous build deleted
+                fi
+
+                docker build -t http-server:build --file Dockerfile.staging . 
+                echo Artifact build completed
+                """
+            }
+        }
+        stage("Deploy build") {
+            steps {
+                echo "Deploying build, if failed deploy backup"
+                sh """
+                if docker container rm -f http-server; then
+	                echo Stopped previous build instance
+                fi
+
+                if ! docker run --restart on-failure:5 -d --name http-server -p 5000:80 http-server:build; then
+                   echo Application is running on port 80
+                fi
+                """
+            }
         }
     }
 }
